{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-hello-world
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}
    - q2-types {{ qiime2_epoch }}

test:
  requires:
    - pytest
  imports:
    - q2_hello_world
    - qiime2.plugins.hello_world
  commands:
    - pytest q2_hello_world --pyargs q2_hello_world

about:
  home: https://example.com
  license: BSD-3-Clause
  license_family: BSD
