name: Test and lint

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: my-environment
        environment-file: environments/q2-hello-world-qiime2-tiny-2024.5.yml
        auto-activate-base: false

    - name: Install plugin
      shell: bash -l {0}
      run: make install

    - name: Run tests
      shell: bash -l {0}
      run: make test

    - name: Run flake8
      shell: bash -l {0}
      run: |
       pip install flake8
       flake8 .

